services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        user: tip-test
        uid: 1500
    container_name: tip-test
    restart: unless-stopped
    working_dir: /var/www/tip-test
    volumes:
      - ./:/var/www/tip-test
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - tip-test
      - external_db_network
    ports:
      - "1200:9000"
    depends_on:
      - db



  db:
    image: mariadb:10.5
    container_name: tip-test-db
    restart: unless-stopped
    command: --max_allowed_packet=67108864
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "1201:3306"
    networks:
      - tip-test
      - external_db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tip-test-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 256M
    ports:
      - "1202:80"
    networks:
      - tip-test

networks:
  tip-test:
    driver: bridge
  external_db_network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
